# Application Settings
[app]
width = 870
max_height = 810
scroll_speed = 0.4
border_radius = 8.0
auto_scroll = false

# Font Configuration
[font]
path = "../../fonts/JetBrainsMono-Regular.ttf"
size = 20.0

# Color Scheme
[colors]
blue = 20
green = 20
red = 20
alpha_multiplier = 230.0

# Keybindings
[keybindings]
show_hide = "Ctrl+X"
type_text = "Ctrl+I"
take_screenshot = "Ctrl+Q"
record_audio = "Ctrl+M"
solve = "Ctrl+Enter"
clear = "Ctrl+G"
switch_to_workspace = "Alt"

# Providers

[Ollama]
api_base="http://localhost:11434/v1/chat/completions"
model="gemma3:4b"
max_tokens=128000
temperature=0.7
top_p=1.0

[OpenRouter]
api_base="https://openrouter.ai/api/v1/chat/completions"
model="deepseek/deepseek-r1-0528"
max_tokens=128000
temperature= 0.0
top_p= 1.0

[Gemini]
api_base="https://generativelanguage.googleapis.com/v1beta/models/{model}"
model="gemini-2.5-flash"
max_tokens=65535
temperature= 0.7
top_p= 1.0

[OpenAI]
api_base="https://api.openai.com/v1/chat/completions"
model="gpt-4.1-mini"
max_tokens=32768
temperature= 0.7
top_p= 1.0

[Claude]
api_base="https://api.anthropic.com/v1/messages"
model="claude-sonnet-4-20250514"
max_tokens=10000
temperature= 0.7
top_p= 1.0

[Xai]
api_base="https://api.x.ai/v1/chat/completions"
model="grok-4-0709"
max_tokens=10000
temperature= 0.7
top_p= 1.0

