[Ollama]
api_base="http://localhost:11434/v1/chat/completions"
model="gemma3:4b"
max_tokens=128000
temperature=0.7
top_p=1.0

[Gemini]
api_base="https://generativelanguage.googleapis.com/v1beta/models/{model}"
model="gemini-2.5-flash"
max_tokens=65535
temperature= 0.7
top_p= 1.0

[OpenAI]
api_base="https://api.openai.com/v1/chat/completions"
model="gpt-4.1-mini"
max_tokens=32768
temperature= 0.7
top_p= 1.0

[Claude]
api_base="https://api.anthropic.com/v1/messages"
model="claude-sonnet-4-20250514"
max_tokens=10000
temperature= 0.7
top_p= 1.0

[Xai]
api_base="https://api.x.ai/v1/chat/completions"
model="grok-4-0709"
max_tokens=10000
temperature= 0.7
top_p= 1.0

